M48
; DRILL file {KiCad 9.0.1} date 2026-07-16T12:47:56-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-16T12:47:56-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X154.0Y-30.0
X154.0Y-76.0
X154.0Y-122.0
X184.0Y-30.0
X184.0Y-76.0
X184.0Y-122.0
M30
